/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_RhoConf */

#ifndef _Included_com_rhomobile_rhodes_RhoConf
#define _Included_com_rhomobile_rhodes_RhoConf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_RhoConf
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoConf_getString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhoConf
 * Method:    getInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhodes_RhoConf_getInt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhoConf
 * Method:    getBool
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rhomobile_rhodes_RhoConf_getBool
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhoConf
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoConf_setString
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhoConf
 * Method:    setInt
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoConf_setInt
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_rhomobile_rhodes_RhoConf
 * Method:    setBoolean
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoConf_setBoolean
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_rhomobile_rhodes_RhoConf
 * Method:    isExist
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rhomobile_rhodes_RhoConf_isExist
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
