/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_socket_RhoSocketImpl */

#ifndef _Included_com_rhomobile_rhodes_socket_RhoSocketImpl
#define _Included_com_rhomobile_rhodes_socket_RhoSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_socket_RhoSocketImpl
 * Method:    initImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_socket_RhoSocketImpl_initImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rhomobile_rhodes_socket_RhoSocketImpl
 * Method:    closeImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_socket_RhoSocketImpl_closeImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rhomobile_rhodes_socket_RhoSocketImpl
 * Method:    getOptionImpl
 * Signature: (II)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_rhomobile_rhodes_socket_RhoSocketImpl_getOptionImpl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_rhomobile_rhodes_socket_RhoSocketImpl
 * Method:    setOptionImpl
 * Signature: (IILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_socket_RhoSocketImpl_setOptionImpl
  (JNIEnv *, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
