/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_RhoMenu */

#ifndef _Included_com_rhomobile_rhodes_RhoMenu
#define _Included_com_rhomobile_rhodes_RhoMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    getMenuSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhodes_RhoMenu_getMenuSize
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    getMenuItemLabel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoMenu_getMenuItemLabel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    getMenuItemType
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoMenu_getMenuItemType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    getMenuItemUrl
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoMenu_getMenuItemUrl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
