/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_SplashScreen */

#ifndef _Included_com_rhomobile_rhodes_SplashScreen
#define _Included_com_rhomobile_rhodes_SplashScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_SplashScreen
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_SplashScreen_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_SplashScreen
 * Method:    nativeHide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_SplashScreen_nativeHide
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
