#!/bin/sh


if [ "$RHO_PLATFORM" = "android" ]; then

cd platform/android
rake --trace

elif [ "$RHO_PLATFORM" = "iphone" ]; then

cd platform/iphone
rake --trace

elif [ "$RHO_PLATFORM" = "osx" ]; then

cd platform/qt
rake --trace

fi
