//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsolatedStorageExplorerClient.ClientStreamingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientStreamingService.IClientStreamingService", CallbackContract=typeof(IsolatedStorageExplorerClient.ClientStreamingService.IClientStreamingServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IClientStreamingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientStreamingService/BeginUploadStream", ReplyAction="http://tempuri.org/IClientStreamingService/BeginUploadStreamResponse")]
        System.Guid BeginUploadStream(System.Guid clientSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientStreamingService/BeginDownloadStream", ReplyAction="http://tempuri.org/IClientStreamingService/BeginDownloadStreamResponse")]
        System.Guid BeginDownloadStream(System.Guid clientSessionId);
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IClientStreamingService/EndStream", ReplyAction="http://tempuri.org/IClientStreamingService/EndStreamResponse")]
        void EndStream();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientStreamingServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientStreamingService/GetNextChunk", ReplyAction="http://tempuri.org/IClientStreamingService/GetNextChunkResponse")]
        byte[] GetNextChunk();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IClientStreamingService/DownloadStreamChunkAvailable")]
        void DownloadStreamChunkAvailable(byte[] chunk, long bytesLeft);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientStreamingServiceChannel : IsolatedStorageExplorerClient.ClientStreamingService.IClientStreamingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientStreamingServiceClient : System.ServiceModel.DuplexClientBase<IsolatedStorageExplorerClient.ClientStreamingService.IClientStreamingService>, IsolatedStorageExplorerClient.ClientStreamingService.IClientStreamingService {
        
        public ClientStreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ClientStreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ClientStreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientStreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientStreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public System.Guid BeginUploadStream(System.Guid clientSessionId) {
            return base.Channel.BeginUploadStream(clientSessionId);
        }
        
        public System.Guid BeginDownloadStream(System.Guid clientSessionId) {
            return base.Channel.BeginDownloadStream(clientSessionId);
        }
        
        public void EndStream() {
            base.Channel.EndStream();
        }
    }
}
