def build_extension(name)
  require File.join($rootdir, 'lib/build/jake.rb')
  args = ['-o', 'Makefile', '-r', '-spec', $qmake_spec, "#{name}.pro", 'CONFIG-=debug', 'CONFIG+=release', 'CONFIG+=no_fixpath', "RHODES_ROOT='#{$rootdir}'", $qmakevars]
  puts Jake.run($qmake,args)
  fail "[qmake #{name}.pro]" unless $? == 0
  #puts Jake.run($make, ['clean'])
  fail "[make clean]" unless $? == 0
  if (ENV['RHO_PLATFORM'] == 'win32')
    puts Jake.run($make, ['release'])
  else
    puts Jake.run($make, ['all'])
  end
  fail "[make all]" unless $? == 0
end

namespace "build" do
  task :config do
    $platform = ENV['RHO_PLATFORM']
    raise "RHO_PLATFORM is not set" if $platform.nil?
    $rootdir = ENV['RHO_ROOT']
    raise "RHO_ROOT is not set" if $rootdir.nil?
    $qmake = ENV['RHO_QMAKE']
    raise "RHO_QMAKE is not set" if $qmake.nil?
    $qmake_spec = ENV['RHO_QMAKE_SPEC']
    raise "RHO_QMAKE_SPEC is not set" if $qmake_spec.nil?
    $qmakevars = ENV['RHO_QMAKE_VARS']
    if $platform == 'win32'
      $make = 'nmake'
    else
      $make = 'make'
    end
  end

  task :all => :config do
    build_extension('<%= namecamelcase() %>')
  end
end

task :default => "build:all"
