#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_ASSERT_H 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_TLSV1_1_METHOD 1
#define HAVE_TLSV1_2_METHOD 1
#define HAVE_EVP_CIPHER_CTX_NEW 1
#define HAVE_EVP_CIPHER_CTX_FREE 1
#define HAVE_SSL_CTX_CLEAR_OPTIONS 1
#define HAVE_ASN1_TIME_ADJ 1
#define HAVE_EVP_CIPHER_CTX_COPY 1
#define HAVE_EVP_PKEY_BASE_ID 1
#define HAVE_HMAC_CTX_COPY 1
#define HAVE_PKCS5_PBKDF2_HMAC 1
#define HAVE_X509_NAME_HASH_OLD 1
#define HAVE_X509_STORE_CTX_GET0_CURRENT_CRL 1
#define HAVE_X509_STORE_SET_VERIFY_CB 1
#define HAVE_I2D_ASN1_SET_ANY 1
#define HAVE_SSL_SET_TLSEXT_HOST_NAME 1
#define HAVE_EVP_PKEY_GET0 1
#define HAVE_SSL_CTX_SET_NEXT_PROTO_SELECT_CB 1
#define HAVE_AUTHENTICATED_ENCRYPTION 1
#define HAVE_EC_CURVE_NIST2NID 1
#define HAVE_X509_REVOKED_DUP 1
#define HAVE_X509_STORE_CTX_GET0_STORE 1
#define HAVE_SSL_CTX_SET_ALPN_SELECT_CB 1
#define HAVE_SSL_CTX_SET1_CURVES_LIST 1
#define HAVE_SSL_CTX_SET_ECDH_AUTO 1
#define HAVE_SSL_GET_SERVER_TMP_KEY 1
#define HAVE_SSL_IS_SERVER 1
#define HAVE_OPENSSL_110_THREADING_API 1
#define HAVE_OPAQUE_OPENSSL 1
#define HAVE_BN_GENCB_NEW 1
#define HAVE_BN_GENCB_FREE 1
#define HAVE_BN_GENCB_GET_ARG 1
#define HAVE_EVP_MD_CTX_NEW 1
#define HAVE_EVP_MD_CTX_FREE 1
#define HAVE_HMAC_CTX_NEW 1
#define HAVE_HMAC_CTX_FREE 1
#define HAVE_X509_STORE_GET_EX_DATA 1
#define HAVE_X509_STORE_SET_EX_DATA 1
#define HAVE_X509_CRL_GET0_SIGNATURE 1
#define HAVE_X509_REQ_GET0_SIGNATURE 1
#define HAVE_X509_REVOKED_GET0_SERIALNUMBER 1
#define HAVE_X509_REVOKED_GET0_REVOCATIONDATE 1
#define HAVE_X509_GET0_TBS_SIGALG 1
#define HAVE_X509_STORE_CTX_GET0_UNTRUSTED 1
#define HAVE_X509_STORE_CTX_GET0_CERT 1
#define HAVE_X509_STORE_CTX_GET0_CHAIN 1
#define HAVE_OCSP_SINGLERESP_GET0_ID 1
#define HAVE_SSL_CTX_GET_CIPHERS 1
#define HAVE_X509_UP_REF 1
#define HAVE_X509_CRL_UP_REF 1
#define HAVE_X509_STORE_UP_REF 1
#define HAVE_SSL_SESSION_UP_REF 1
#define HAVE_EVP_PKEY_UP_REF 1
#define HAVE_SSL_CTX_SET_MIN_PROTO_VERSION 1
#define HAVE_SSL_CTX_GET_SECURITY_LEVEL 1
#define HAVE_X509_GET0_NOTBEFORE 1
#define HAVE_SSL_SESSION_GET_PROTOCOL_VERSION 1

#define OPENSSL_NO_ENGINE
//#define OPENSSL_API_COMPAT 0x10002000L

#endif
