#ifndef __SPIRIT_KEYBOARD_HOOK__H__
#define __SPIRIT_KEYBOARD_HOOK__H__

#ifdef __cplusplus
#define EXTERN_C extern "C"
#else
#define EXTERN_C extern
#endif

#define SPIRIT_KEYBOARD_HOOK_CALL_TYPE           __cdecl
#define SPIRIT_KEYBOARD_HOOK_EXPORT_SYMBOL       __declspec(dllexport)
#define SPIRIT_KEYBOARD_HOOK_IMPORT_SYMBOL       __declspec(dllimport)

#ifdef SPIRIT_KEYBOARD_HOOK_STATIC
    #define SPIRIT_KEYBOARD_HOOK_SYMBOL
#else // SPIRIT_KEYBOARD_HOOK_STATIC
    #ifdef SPIRIT_KEYBOARD_HOOK_EXPORT
        #define SPIRIT_KEYBOARD_HOOK_SYMBOL SPIRIT_KEYBOARD_HOOK_EXPORT_SYMBOL
    #else // SPIRIT_KEYBOARD_HOOK_EXPORT
        #define SPIRIT_KEYBOARD_HOOK_SYMBOL SPIRIT_KEYBOARD_HOOK_IMPORT_SYMBOL
    #endif // SPIRIT_KEYBOARD_HOOK_EXPORT
#endif // SPIRIT_KEYBOARD_HOOK_STATIC

typedef struct
{
    DWORD   vkCode;
    DWORD   scCode;
    DWORD   dwFlags;
    DWORD   dwTime;
    DWORD   dwInfo;
} sSpiritKeyboardHookKey;

typedef unsigned int (CALLBACK *SPIRIT_KEYBOARD_HOOK_CALLBACK)(WPARAM, LPARAM);

EXTERN_C SPIRIT_KEYBOARD_HOOK_SYMBOL unsigned int SPIRIT_KEYBOARD_HOOK_CALL_TYPE SpiritKeyboardHookInit(SPIRIT_KEYBOARD_HOOK_CALLBACK Func);
EXTERN_C SPIRIT_KEYBOARD_HOOK_SYMBOL unsigned int SPIRIT_KEYBOARD_HOOK_CALL_TYPE SpiritKeyboardHookDeinit();
EXTERN_C SPIRIT_KEYBOARD_HOOK_SYMBOL unsigned int SPIRIT_KEYBOARD_HOOK_CALL_TYPE SpiritKeyboardHookGetVersion(const char **ppVersion);

#endif // __SPIRIT_KEYBOARD_HOOK__H__