/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.rhomobile.rhodes;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int home=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int info=0x7f020003;
        public static final int next=0x7f020004;
        public static final int refresh=0x7f020005;
        public static final int sync=0x7f020006;
    }
    public static final class id {
        public static final int about=0x7f060006;
        public static final int navigation_back=0x7f060004;
        public static final int navigation_forward=0x7f060003;
        public static final int navigation_home=0x7f060002;
        public static final int refresh=0x7f060005;
        public static final int sync=0x7f060007;
        public static final int text=0x7f060000;
        public static final int webview=0x7f060001;
    }
    public static final class layout {
        public static final int dialog_activity=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int options=0x7f050000;
    }
    public static final class string {
        public static final int about=0x7f040006;
        public static final int about_rhodes=0x7f04000c;
        public static final int app_name=0x7f040000;
        public static final int back=0x7f040004;
        public static final int exit=0x7f040007;
        public static final int forward=0x7f040003;
        public static final int home=0x7f040001;
        public static final int http_service_label=0x7f04000b;
        public static final int http_service_started=0x7f04000a;
        public static final int navigation=0x7f040005;
        public static final int options_label=0x7f040009;
        public static final int refresh=0x7f040002;
        public static final int sync=0x7f040008;
    }
}
