require 'rubygems'
require 'hoe'

task :default => [:spec]

Hoe.spec 'rhodes-generator' do
  developer 'Rhomobile Dev', 'dev@rhomobile.com'
end

desc "Run the specs under spec"
Spec::Rake::SpecTask.new do |t|
  t.spec_opts = ['--options', "spec/spec.opts"]
  t.spec_files = FileList['spec/**/*_spec.rb']
  t.rcov = true
  t.rcov_opts = ['--include',
                 '"bin/*,generators/*"',
                 '-x',
                 'spec,gems',
                 '--text-report',
                 '--html']
end
