CONFIG += c++14
DEFINES += RHODES_VERSION_LIBRARY

TEMPLATE = subdirs
SUBDIRS = rubylib rholib sqlite3 syncengine

CONFIG += ordered
SUBDIRS += rhodes

QMAKE_CXXFLAGS_RELEASE += -MP9
QMAKE_CXXFLAGS_DEBUG += -MP9
