// Auto-generated by config:altLinux. Do not edit manually.
#pragma once
#define ALTGTK_APP_NAME "inventoryDemo"
#define ALTGTK_APP_VERSION "1.0.12"
#define ALTGTK_VENDOR "rhomobile"
#define ALTGTK_APP_ID "com.rhomobile.inventorydemo"
#define ALTGTK_SDK_VERSION "7.4.0"
