$:.unshift(File.join(File.dirname(__FILE__), 'lib'))
require 'rubygems'
require 'spec/rake/spectask'
require 'rake/gempackagetask'
require 'rake/clean'

Spec::Rake::SpecTask.new(:default) do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
  t.spec_opts = ['--options', 'spec/spec.opts']
  t.rcov = true
  t.rcov_opts = ['--include', 
		 '"lib/rhom/*,lib/rho/*"',
		 '--exclude', 
		 '"spec/*,lib/date*,lib/rational*,lib/time*,lib/pairparser.rb,/Library/Ruby/Gems/*,/var/lib/gems/*,/usr/lib/ruby"',
		 '--text-report',
		 '--html']	
end

require File.join(File.dirname(__FILE__), 'spec/stubs')
SPEC = eval(File.read("#{File.dirname(__FILE__)}/rhodes.gemspec"))
Rake::GemPackageTask.new(SPEC) do |p|
  p.gem_spec = SPEC
end
