/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhoconnect_RhoConnectObjectNotify */

#ifndef _Included_com_rhomobile_rhoconnect_RhoConnectObjectNotify
#define _Included_com_rhomobile_rhoconnect_RhoConnectObjectNotify
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
