/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhoconnect_RhomModel */

#ifndef _Included_com_rhomobile_rhoconnect_RhomModel
#define _Included_com_rhomobile_rhoconnect_RhomModel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhoconnect_RhomModel_MODEL_TYPE_PROPERTY_BAG
#define com_rhomobile_rhoconnect_RhomModel_MODEL_TYPE_PROPERTY_BAG 0L
#undef com_rhomobile_rhoconnect_RhomModel_MODEL_TYPE_FIXED_SCHEMA
#define com_rhomobile_rhoconnect_RhomModel_MODEL_TYPE_FIXED_SCHEMA 1L
#undef com_rhomobile_rhoconnect_RhomModel_SYNC_TYPE_NONE
#define com_rhomobile_rhoconnect_RhomModel_SYNC_TYPE_NONE 0L
#undef com_rhomobile_rhoconnect_RhomModel_SYNC_TYPE_INCREMENTAL
#define com_rhomobile_rhoconnect_RhomModel_SYNC_TYPE_INCREMENTAL 1L
#undef com_rhomobile_rhoconnect_RhomModel_SYNC_TYPE_BULK_ONLY
#define com_rhomobile_rhoconnect_RhomModel_SYNC_TYPE_BULK_ONLY 2L
/*
 * Class:     com_rhomobile_rhoconnect_RhomModel
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhoconnect_RhomModel_init
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhoconnect_RhomModel
 * Method:    syncByName
 * Signature: (Ljava/lang/String;)Lcom/rhomobile/rhoconnect/RhoConnectNotify;
 */
JNIEXPORT jobject JNICALL Java_com_rhomobile_rhoconnect_RhomModel_syncByName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
