/*------------------------------------------------------------------------
* (The MIT License)
*
* Copyright (c) 2008-2011 Rhomobile, Inc.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*
* http://rhomobile.com
*------------------------------------------------------------------------*/

RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_BOOLEAN, "java/lang/Boolean")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_INTEGER, "java/lang/Integer")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_FLOAT, "java/lang/Float")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_DOUBLE, "java/lang/Double")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_STRING, "java/lang/String")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_RUNTIME_EXCEPTION, "java/lang/RuntimeException")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_ARRAYLIST, "java/util/ArrayList")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_VECTOR, "java/util/Vector")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_SET, "java/util/Set")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_MAP, "java/util/Map")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_HASHMAP, "java/util/HashMap")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_ITERATOR, "java/util/Iterator")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_DATE, "java/util/Date")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_BUFFEREDREADER, "java/io/BufferedReader")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_FILEDESCRIPTOR, "java/io/FileDescriptor")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_INPUTSTREAMREADER, "java/io/InputStreamReader")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_INET4ADDRESS, "java/net/Inet4Address")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_RHOCRYPTIMPL, "com/rhomobile/rhodes/RhoCryptImpl")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_RHOSOCKADDR, "com/rhomobile/rhodes/socket/RhoSockAddr")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_SSLIMPL, "com/rhomobile/rhodes/socket/SSLImpl")
RHODES_DEFINE_JAVA_CLASS(RHODES_JAVA_CLASS_RHOFILEAPI, "com/rhomobile/rhodes/file/RhoFileApi")
RHODES_DEFINE_JAVA_CLASS(RHOCONNECT_JAVA_CLASS_CLIENT, "com/rhomobile/rhoconnect/RhoConnectClient")
RHODES_DEFINE_JAVA_CLASS(RHOCONNECT_JAVA_CLASS_RHOMMODEL, "com/rhomobile/rhoconnect/RhomModel")
RHODES_DEFINE_JAVA_CLASS(RHOCONNECT_JAVA_CLASS_NOTIFY, "com/rhomobile/rhoconnect/RhoConnectNotify")
RHODES_DEFINE_JAVA_CLASS(RHOCONNECT_JAVA_CLASS_NOTIFY_DELEGATE, "com/rhomobile/rhoconnect/RhoConnectNotify$IDelegate")
RHODES_DEFINE_JAVA_CLASS(RHOCONNECT_JAVA_CLASS_OBJECTNOTIFY, "com/rhomobile/rhoconnect/RhoConnectObjectNotify")
RHODES_DEFINE_JAVA_CLASS(RHOCONNECT_JAVA_CLASS_OBJECTNOTIFY_DELEGATE, "com/rhomobile/rhoconnect/RhoConnectObjectNotify$IDelegate")
