
/**
 * 
 */
package com.rho.rhoelements.common;

/**
 * @author Automatically generated by Ant
 * Contains the OEM strings for license validation.
 */
public class Oem
{
public static final boolean testmode = false;
		
/**
 * Allowed OEM's
*/
public static final String[] AllowedOEM = {
		"symbol",};
/**
* Exempt products
*/
public static final String[] ExemptProducts = {
		"PS4070","MC17","MK500","MK4000","MK3000",};
/**
* Validated products
*/
public static final String[] ValidatedProducts = {
		"MC3000C42B","MC9000G","MC50","MC3000C50B","MC9000K","MC9000S","sdk","ET1","MC40N0",};}