/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_RhoLogConf */

#ifndef _Included_com_rhomobile_rhodes_RhoLogConf
#define _Included_com_rhomobile_rhodes_RhoLogConf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    getEnabledCategories
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoLogConf_getEnabledCategories
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    setEnabledCategories
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoLogConf_setEnabledCategories
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    getDisabledCategories
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoLogConf_getDisabledCategories
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    setDisabledCategories
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoLogConf_setDisabledCategories
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    getMinSeverity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhodes_RhoLogConf_getMinSeverity
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    setMinSeverity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoLogConf_setMinSeverity
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    saveToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoLogConf_saveToFile
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    clearLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoLogConf_clearLog
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    getLogText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoLogConf_getLogText
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    getLogTextPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhodes_RhoLogConf_getLogTextPos
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhoLogConf
 * Method:    sendLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoLogConf_sendLog
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
