/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_Logger */

#ifndef _Included_com_rhomobile_rhodes_Logger
#define _Included_com_rhomobile_rhodes_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_Logger
 * Method:    eNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Logger_eNative
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_Logger
 * Method:    wNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Logger_wNative
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_Logger
 * Method:    iNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Logger_iNative
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_Logger
 * Method:    dNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Logger_dNative
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_Logger
 * Method:    tNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Logger_tNative
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
