/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_RhodesService */

#ifndef _Included_com_rhomobile_rhodes_RhodesService
#define _Included_com_rhomobile_rhodes_RhodesService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_RhodesService_RHO_SPLASH_VIEW
#define com_rhomobile_rhodes_RhodesService_RHO_SPLASH_VIEW 1L
#undef com_rhomobile_rhodes_RhodesService_RHO_MAIN_VIEW
#define com_rhomobile_rhodes_RhodesService_RHO_MAIN_VIEW 2L
#undef com_rhomobile_rhodes_RhodesService_RHO_TOOLBAR_VIEW
#define com_rhomobile_rhodes_RhodesService_RHO_TOOLBAR_VIEW 3L
/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    initClassLoader
 * Signature: (Ljava/lang/ClassLoader;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_initClassLoader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    createRhodesApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_createRhodesApp
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    startRhodesApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_startRhodesApp
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    doSyncAllSources
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_doSyncAllSources
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    getOptionsUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesService_getOptionsUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    getStartUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesService_getStartUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    getCurrentUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesService_getCurrentUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    getAppBackUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesService_getAppBackUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    getBlobPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesService_getBlobPath
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    normalizeUrl
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesService_normalizeUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    loadUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_loadUrl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    navigateBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_navigateBack
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    doRequest
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_doRequest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    callActivationCallback
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_callActivationCallback
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    makeLink
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_makeLink
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    onScreenOrientationChanged
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_onScreenOrientationChanged
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    nativeInitPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_nativeInitPath
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
