/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_file_RhoFileApi */

#ifndef _Included_com_rhomobile_rhodes_file_RhoFileApi
#define _Included_com_rhomobile_rhodes_file_RhoFileApi
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_file_RhoFileApi_MAX_SIZE
#define com_rhomobile_rhodes_file_RhoFileApi_MAX_SIZE 2097152L
/*
 * Class:     com_rhomobile_rhodes_file_RhoFileApi
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_file_RhoFileApi_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_file_RhoFileApi
 * Method:    updateStatTable
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_file_RhoFileApi_updateStatTable
  (JNIEnv *, jclass, jstring, jstring, jlong, jlong);

/*
 * Class:     com_rhomobile_rhodes_file_RhoFileApi
 * Method:    normalizePath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_file_RhoFileApi_normalizePath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
