/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_socket_SSLImpl */

#ifndef _Included_com_rhomobile_rhodes_socket_SSLImpl
#define _Included_com_rhomobile_rhodes_socket_SSLImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_socket_SSLImpl
 * Method:    getRemoteSockAddr
 * Signature: (I)Lcom/rhomobile/rhodes/socket/RhoSockAddr;
 */
JNIEXPORT jobject JNICALL Java_com_rhomobile_rhodes_socket_SSLImpl_getRemoteSockAddr
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
