/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_mapview_MapView */

#ifndef _Included_com_rhomobile_rhodes_mapview_MapView
#define _Included_com_rhomobile_rhodes_mapview_MapView
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_mapview_MapView_DEBUG
#define com_rhomobile_rhodes_mapview_MapView_DEBUG 0L
/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    attachToNativeDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mapview_MapView_attachToNativeDevice
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    setSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mapview_MapView_setSize
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    paint
 * Signature: (JLandroid/graphics/Canvas;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mapview_MapView_paint
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
