/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_geolocation_GeoLocationImpl */

#ifndef _Included_com_rhomobile_rhodes_geolocation_GeoLocationImpl
#define _Included_com_rhomobile_rhodes_geolocation_GeoLocationImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_geolocation_GeoLocationImpl_TIMEOUT_STOP
#define com_rhomobile_rhodes_geolocation_GeoLocationImpl_TIMEOUT_STOP -1LL
/*
 * Class:     com_rhomobile_rhodes_geolocation_GeoLocationImpl
 * Method:    geoCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_geolocation_GeoLocationImpl_geoCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_geolocation_GeoLocationImpl
 * Method:    geoCallbackError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_geolocation_GeoLocationImpl_geoCallbackError
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_geolocation_GeoLocationImpl
 * Method:    geoCallbackStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_geolocation_GeoLocationImpl_geoCallbackStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
