/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_RhodesAppOptions */

#ifndef _Included_com_rhomobile_rhodes_RhodesAppOptions
#define _Included_com_rhomobile_rhodes_RhodesAppOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_RhodesAppOptions
 * Method:    getOptionsUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesAppOptions_getOptionsUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhodesAppOptions
 * Method:    getStartUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesAppOptions_getStartUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhodesAppOptions
 * Method:    getCurrentUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesAppOptions_getCurrentUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhodesAppOptions
 * Method:    getAppBackUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesAppOptions_getAppBackUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhodesAppOptions
 * Method:    getBlobPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesAppOptions_getBlobPath
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
