/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_mapview_MapView */

#ifndef _Included_com_rhomobile_rhodes_mapview_MapView
#define _Included_com_rhomobile_rhodes_mapview_MapView
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_mapview_MapView_DEBUG
#define com_rhomobile_rhodes_mapview_MapView_DEBUG 0L
#undef com_rhomobile_rhodes_mapview_MapView_ZOOM_ANIMATION_ENABLED
#define com_rhomobile_rhodes_mapview_MapView_ZOOM_ANIMATION_ENABLED 1L
#undef com_rhomobile_rhodes_mapview_MapView_ZOOM_RESOLUTION
#define com_rhomobile_rhodes_mapview_MapView_ZOOM_RESOLUTION 50L
#undef com_rhomobile_rhodes_mapview_MapView_ENABLE_MULTI_TOUCH
#define com_rhomobile_rhodes_mapview_MapView_ENABLE_MULTI_TOUCH 0L
/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    setSize
 * Signature: (Lcom/rhomobile/rhodes/mapview/MapView;JII)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mapview_MapView_setSize
  (JNIEnv *, jobject, jobject, jlong, jint, jint);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    setPinImage
 * Signature: (JLandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mapview_MapView_setPinImage
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    minZoom
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhodes_mapview_MapView_minZoom
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    maxZoom
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhodes_mapview_MapView_maxZoom
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    zoom
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhodes_mapview_MapView_zoom
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    setZoom
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mapview_MapView_setZoom
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    move
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mapview_MapView_move
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    paint
 * Signature: (JLandroid/graphics/Canvas;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mapview_MapView_paint
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_rhomobile_rhodes_mapview_MapView
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mapview_MapView_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
