/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_RhodesService */

#ifndef _Included_com_rhomobile_rhodes_RhodesService
#define _Included_com_rhomobile_rhodes_RhodesService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_RhodesService_DEBUG
#define com_rhomobile_rhodes_RhodesService_DEBUG 0L
#undef com_rhomobile_rhodes_RhodesService_DOWNLOAD_PACKAGE_ID
#define com_rhomobile_rhodes_RhodesService_DOWNLOAD_PACKAGE_ID 1L
/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    initClassLoader
 * Signature: (Ljava/lang/ClassLoader;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_initClassLoader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    createRhodesApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_createRhodesApp
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    startRhodesApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_startRhodesApp
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    doSyncAllSources
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_doSyncAllSources
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    doSyncSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_doSyncSource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    normalizeUrl
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesService_normalizeUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    doRequest
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_doRequest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    loadUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_loadUrl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    navigateBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_navigateBack
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    nativeInitPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_nativeInitPath
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    onScreenOrientationChanged
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_onScreenOrientationChanged
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    callUiCreatedCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_callUiCreatedCallback
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    callUiDestroyedCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_callUiDestroyedCallback
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    callActivationCallback
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_callActivationCallback
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    getBuildConfig
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhodesService_getBuildConfig
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    isOnStartPage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rhomobile_rhodes_RhodesService_isOnStartPage
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    canStartApp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rhomobile_rhodes_RhodesService_canStartApp
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    setPushRegistrationId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesService_setPushRegistrationId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhodes_RhodesService
 * Method:    callPushCallback
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rhomobile_rhodes_RhodesService_callPushCallback
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
