/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_RhoMenu */

#ifndef _Included_com_rhomobile_rhodes_RhoMenu
#define _Included_com_rhomobile_rhodes_RhoMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    allocMenu
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_rhomobile_rhodes_RhoMenu_allocMenu
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    deallocMenu
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhoMenu_deallocMenu
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    getMenuSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhodes_RhoMenu_getMenuSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    getMenuItemLabel
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoMenu_getMenuItemLabel
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    getMenuItemType
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoMenu_getMenuItemType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_rhomobile_rhodes_RhoMenu
 * Method:    getMenuItemUrl
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_RhoMenu_getMenuItemUrl
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
