/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_file_RhoFileApi */

#ifndef _Included_com_rhomobile_rhodes_file_RhoFileApi
#define _Included_com_rhomobile_rhodes_file_RhoFileApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_file_RhoFileApi
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_file_RhoFileApi_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
