/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_signature_Signature */

#ifndef _Included_com_rhomobile_rhodes_signature_Signature
#define _Included_com_rhomobile_rhodes_signature_Signature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_signature_Signature
 * Method:    callback
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_signature_Signature_callback
  (JNIEnv *, jclass, jstring, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
