/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_mainview_SplashScreen */

#ifndef _Included_com_rhomobile_rhodes_mainview_SplashScreen
#define _Included_com_rhomobile_rhodes_mainview_SplashScreen
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_mainview_SplashScreen_DEBUG
#define com_rhomobile_rhodes_mainview_SplashScreen_DEBUG 0L
/*
 * Class:     com_rhomobile_rhodes_mainview_SplashScreen
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mainview_SplashScreen_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_mainview_SplashScreen
 * Method:    nativeHide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_mainview_SplashScreen_nativeHide
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_mainview_SplashScreen
 * Method:    howLongWaitMs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhodes_mainview_SplashScreen_howLongWaitMs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
