/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_api_MethodResult */

#ifndef _Included_com_rhomobile_rhodes_api_MethodResult
#define _Included_com_rhomobile_rhodes_api_MethodResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_api_MethodResult
 * Method:    nativeSetBoolean
 * Signature: (ZLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_api_MethodResult_nativeSetBoolean
  (JNIEnv *, jclass, jboolean, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_api_MethodResult
 * Method:    nativeSetInteger
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_api_MethodResult_nativeSetInteger
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_api_MethodResult
 * Method:    nativeSetDouble
 * Signature: (DLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_api_MethodResult_nativeSetDouble
  (JNIEnv *, jclass, jdouble, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_api_MethodResult
 * Method:    nativeSetString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_api_MethodResult_nativeSetString
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_api_MethodResult
 * Method:    nativeSetStringList
 * Signature: (Ljava/util/List;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_api_MethodResult_nativeSetStringList
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_api_MethodResult
 * Method:    nativeSetStringMap
 * Signature: (Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_api_MethodResult_nativeSetStringMap
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_api_MethodResult
 * Method:    nativeSetArgError
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_api_MethodResult_nativeSetArgError
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_api_MethodResult
 * Method:    nativeSetError
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_api_MethodResult_nativeSetError
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
