/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_alert_PopupActivity */

#ifndef _Included_com_rhomobile_rhodes_alert_PopupActivity
#define _Included_com_rhomobile_rhodes_alert_PopupActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_alert_PopupActivity
 * Method:    doCallback
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_alert_PopupActivity_doCallback
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
