/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_RhodesApplication */

#ifndef _Included_com_rhomobile_rhodes_RhodesApplication
#define _Included_com_rhomobile_rhodes_RhodesApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_RhodesApplication
 * Method:    setStartParameters
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_RhodesApplication_setStartParameters
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
