/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_bluetooth_RhoBluetoothManager */

#ifndef _Included_com_rhomobile_rhodes_bluetooth_RhoBluetoothManager
#define _Included_com_rhomobile_rhodes_bluetooth_RhoBluetoothManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_bluetooth_RhoBluetoothManager_BTC_OK
#define com_rhomobile_rhodes_bluetooth_RhoBluetoothManager_BTC_OK 0L
#undef com_rhomobile_rhodes_bluetooth_RhoBluetoothManager_BTC_CANCEL
#define com_rhomobile_rhodes_bluetooth_RhoBluetoothManager_BTC_CANCEL 2L
#undef com_rhomobile_rhodes_bluetooth_RhoBluetoothManager_BTC_ERROR
#define com_rhomobile_rhodes_bluetooth_RhoBluetoothManager_BTC_ERROR 3L
/*
 * Class:     com_rhomobile_rhodes_bluetooth_RhoBluetoothManager
 * Method:    onCallback
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_bluetooth_RhoBluetoothManager_onCallback
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
