/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_Rhodes */

#ifndef _Included_com_rhomobile_rhodes_Rhodes
#define _Included_com_rhomobile_rhodes_Rhodes
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_Rhodes_ENABLE_PROFILING
#define com_rhomobile_rhodes_Rhodes_ENABLE_PROFILING 0L
#undef com_rhomobile_rhodes_Rhodes_RHO_SPLASH_VIEW
#define com_rhomobile_rhodes_Rhodes_RHO_SPLASH_VIEW 1L
#undef com_rhomobile_rhodes_Rhodes_RHO_MAIN_VIEW
#define com_rhomobile_rhodes_Rhodes_RHO_MAIN_VIEW 2L
#undef com_rhomobile_rhodes_Rhodes_RHO_TOOLBAR_VIEW
#define com_rhomobile_rhodes_Rhodes_RHO_TOOLBAR_VIEW 3L
/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    createRhodesApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_createRhodesApp
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    startRhodesApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_startRhodesApp
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    doSyncAllSources
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_doSyncAllSources
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    getOptionsUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_Rhodes_getOptionsUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    getStartUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_Rhodes_getStartUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    getCurrentUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_Rhodes_getCurrentUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    getAppBackUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_Rhodes_getAppBackUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    getBlobPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_Rhodes_getBlobPath
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    normalizeUrl
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_Rhodes_normalizeUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    loadUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_loadUrl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    navigateBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_navigateBack
  (JNIEnv *, jclass);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    doRequest
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_doRequest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    callActivationCallback
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_callActivationCallback
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    makeLink
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_makeLink
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    initClassLoader
 * Signature: (Ljava/lang/ClassLoader;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_initClassLoader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    nativeInitPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_nativeInitPath
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_rhomobile_rhodes_Rhodes
 * Method:    onScreenOrientationChanged
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Rhodes_onScreenOrientationChanged
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
