/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_camera_Camera */

#ifndef _Included_com_rhomobile_rhodes_camera_Camera
#define _Included_com_rhomobile_rhodes_camera_Camera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_camera_Camera
 * Method:    callback
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
RHO_GLOBAL void JNICALL Java_com_rhomobile_rhodes_camera_Camera_callback
  (JNIEnv *env, jclass, jstring callback_url, jstring body);

#ifdef __cplusplus
}
#endif
#endif
