/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_gcm_GCMRhoListener */

#ifndef _Included_com_rhomobile_rhodes_gcm_GCMRhoListener
#define _Included_com_rhomobile_rhodes_gcm_GCMRhoListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_gcm_GCMRhoListener
 * Method:    nativeAddGCMPushClient
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_gcm_GCMRhoListener_nativeAddGCMPushClient
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
