sdk: ../../.. 
sdkversion: 3.5.0
name: gcm_push_client
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator8.2
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.gcmpushclient
  BundleURLScheme: gcmpushclient
wp:
  productid: '80b879d0-16fc-0130-39e9-3c0754090a18'
android:
  version: 2.3.3
  capabilities:
  - push
  push:
    notifications: none
    sender: 888725080924

extensions: ["json"]
