require File.join(pwd, '../../../../../build/jake.rb')

def build_extension(name)
  dir = File.join($rootdir, "lib/commonAPI/#{name}/ext/platform/osx")
  qmake = "#{$qmake} -o Makefile -r -spec #{$qmake_spec} #{name}.pro QMAKE_MAC_SDK='#{$sdkroot}' CONFIG-=debug CONFIG+=release"

  Jake.run3(qmake           , dir)
  Jake.run3("#{$make} clean", dir)
  Jake.run3("#{$make} all"  , dir)
end

namespace "build" do
  task :config do
    $platform = ENV['RHO_PLATFORM']
    raise "RHO_PLATFORM is not set" if $platform.nil?
    $rootdir = ENV['RHO_ROOT']
    raise "RHO_ROOT is not set" if $rootdir.nil?
    $qmake = ENV['RHO_QMAKE']
    raise "RHO_QMAKE is not set" if $qmake.nil?
    if $platform == 'win32'
      $qmake_spec = 'win32-msvc2010'
      $make = 'nmake'
    else
      $sdkroot = ENV['SDKROOT']
      raise "SDKROOT is not set" if $sdkroot.nil?
      $qmake_spec = 'macx-g++'
      $make = "make"
    end
  end

  task :all => :config do
    build_extension('coreapi')
  end
end

task :default => "build:all"
