#pragma once

//#ifdef APP_BUILD_CAPABILITY_WEBKIT_BROWSER
extern UINT WM_BROWSER_ONDOCUMENTCOMPLETE;
extern UINT WM_BROWSER_ONNAVIGATECOMPLETE;
extern UINT WM_BROWSER_ONTITLECHANGE;
extern UINT WM_BROWSER_ONBEFORENAVIGATE;
extern UINT WM_BROWSER_ONNAVIGATIONTIMEOUT;
extern UINT WM_BROWSER_ONSETSIPSTATE;
extern UINT WM_BROWSER_ONALERTPOPUP;
extern UINT WM_BROWSER_ONNAVIGATIONERROR;
extern UINT WM_BROWSER_ONAUTHENTICATIONREQUEST;
//extern UINT WM_BROWSER_ONGPSDATA;
//#endif //APP_BUILD_CAPABILITY_WEBKIT_BROWSER
