#include <windows.h>

//#include "common/app_build_capabilities.h"
#include "RhoElementsMsgs.h"

//#ifdef APP_BUILD_CAPABILITY_WEBKIT_BROWSER 
UINT WM_BROWSER_ONDOCUMENTCOMPLETE      = ::RegisterWindowMessage(L"RHODES_WM_BROWSER_ONDOCUMENTCOMPLETE");
UINT WM_BROWSER_ONNAVIGATECOMPLETE      = ::RegisterWindowMessage(L"RHODES_WM_BROWSER_ONNAVIGATECOMPLETE");
UINT WM_BROWSER_ONTITLECHANGE           = ::RegisterWindowMessage(L"RHODES_WM_BROWSER_ONTITLECHANGE");
UINT WM_BROWSER_ONBEFORENAVIGATE        = ::RegisterWindowMessage(L"RHODES_WM_BROWSER_ONBEFORENAVIGATE");
UINT WM_BROWSER_ONNAVIGATIONTIMEOUT     = ::RegisterWindowMessage(L"RHODES_WM_BROWSER_ONNAVIGATIONTIMEOUT");
UINT WM_BROWSER_ONNAVIGATIONERROR       = ::RegisterWindowMessage(L"RHODES_WM_BROWSER_ONNAVIGATIONERROR");
UINT WM_BROWSER_ONSETSIPSTATE           = ::RegisterWindowMessage(L"RHODES_WM_BROWSER_ONSETSIPSTATE");
UINT WM_BROWSER_ONALERTPOPUP            = ::RegisterWindowMessage(L"WM_BROWSER_ONALERTPOPUP");
UINT WM_BROWSER_ONAUTHENTICATIONREQUEST = ::RegisterWindowMessage(L"WM_BROWSER_ONAUTHENTICATIONREQUEST");
//UINT WM_BROWSER_ONGPSDATA               = ::RegisterWindowMessage(L"WM_BROWSER_ONGPSDATA");
//#endif
