# -*- makefile -*- Time-stamp: <04/10/17 21:16:38 ptr>
# $Id: Makefile.inc 1460 2005-04-18 21:37:58Z ptr $

PRGNAME = compiler_test
SRC_CPP = ttei1.cpp ttei2.cpp ttei3.cpp ttei4.cpp ttei5.cpp ttei6.cpp ttei7.cpp \
          movable.cpp
SRC_CC = eh.cc
