/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhosync_RhoSyncClient */

#ifndef _Included_com_rhomobile_rhosync_RhoSyncClient
#define _Included_com_rhomobile_rhosync_RhoSyncClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    initialize
 * Signature: ([Lcom/rhomobile/rhosync/RhomModel;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_initialize
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    setSyncServer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_setSyncServer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    setThreadedMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_setThreadedMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    setPollInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_setPollInterval
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    getPollInterval
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_getPollInterval
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    setBulkSyncState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_setBulkSyncState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    getBulkSyncState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_getBulkSyncState
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    setConfigString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_setConfigString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    getConfigString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_getConfigString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    initDatabase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_initDatabase
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    addModels
 * Signature: ([Lcom/rhomobile/rhosync/RhomModel;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_addModels
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    databaseFullResetAndLogout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_databaseFullResetAndLogout
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    isLoggedIn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_isLoggedIn
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    loginWithUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/rhomobile/rhosync/RhoSyncNotify;
 */
JNIEXPORT jobject JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_loginWithUser
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    syncAll
 * Signature: ()Lcom/rhomobile/rhosync/RhoSyncNotify;
 */
JNIEXPORT jobject JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_syncAll
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhosync_RhoSyncClient
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhosync_RhoSyncClient_nativeInit
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
