#sdk: "<%=@sdk_path%>"
sdkversion: <%=Rhodes::VERSION%>
name: <%=@app_name%>
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.<%=@app_name_cleared%>
  BundleURLScheme: <%=@app_name_cleared%>
wp:
  productid: '<%=@productid%>'
symbian:
  uid: '<%=@uid%>'
android:
  version: 2.1

extensions: ["json", "another-extension"]
