//------------------------------------------------------------------
// FILENAME: DShowTestApp.h
//
// Copyright(c) 2003 Symbol Technologies Inc. All rights reserved.
//
// DESCRIPTION:	This is the header that contains information for UI application.
//
// %IF Symbol_Internal
// AUTHOR: Wajra Attale
// CREATION DATE: 01/20/2007
// DERIVED FROM: New File
//
// EDIT HISTORY: No PVCS history for this file
// $Log:   T:/MPA2.0_sandbox/archives/SymbolValueAdd_mpa2/CCL/Camera/DShowCam/test/DShowTestApp/DShowTestApp.h-arc  $
//
//   Rev 1.0   Apr 18 2008 10:17:32   cheung
//Initial revision.
//
//   Rev 1.0   Dec 14 2007 07:21:00   sepalas
//Initial revision.
//
//%End
//------------------------------------------------------------------
#ifndef HEADERFILE_DSTA_
#define HEADERFILE_DSTA_

#pragma once
#include "resourceppc.h"

//#define DEBUG_MODE

#define NO_OF_CAMs 10
#define MY_TIMER 1
#define MY_TIMER2 5
#define NO_OF_IMAGE_PROP 9
#define NO_OF_CAMERA_PROP 8
#define BUF_LENGTH 256
#define MAX_LOADSTRING 256
#define	MARGIN_GAP 3
#define STR_LENGHT 50
#define MAX_FILTER 200
#define MAX_TITLE 100
#define MAX_EXT	10

#define Index0 0
#define Index1 1
#define Index2 2
#define Index3 3
#define Index4 4
#define Index5 5
#define Index6 6
#define Index7 7
#define Index8 8
#define Index9 9

#define IDC_CAPTURE 100
#define IDC_MODE	102
#define IDC_CAMID   104
#define IDC_SLIDER	106
#define IDC_PROP	108
#define IDC_POS		110
#define IDC_PREVIEW 112
#define IDC_STRESS  114
#define IDC_TIMER   116

#define STR_SMODE	 IDS_STRING500
#define STR_VMODE	 IDS_STRING501
#define STR_STILL	 IDS_STRING502
#define STR_VIDEO	 IDS_STRING503
#define STR_CAPTURE	 IDS_STRING504
#define STR_STOP	 IDS_STRING505
#define STR_FOTITLE	 IDS_STRING506
#define STR_FEXT	 IDS_STRING507
#define STR_TRUE	 IDS_STRING508
#define STR_FALSE	 IDS_STRING509
#define STR_GRERROR	 IDS_STRING510
#define STR_FGBERROR IDS_STRING511
#define STR_FGIERROR IDS_STRING512
#define STR_EDIT	 IDS_STRING513
#define STR_BUTTON	 IDS_STRING514
#define STR_STATIC	 IDS_STRING515
#define STR_COMBOBOX IDS_STRING516
#define STR_BLANK	 IDS_STRING517
#define STR_MTITLE   IDS_STRING518
#define STR_FFILTER  IDS_STRING519
#define STR_DEMARKATE IDS_STRING530
#define STR_WM_PAINT  IDS_STRING569
#define STR_MAX	 IDS_STRING570
#define STR_MIN	 IDS_STRING571
#define STR_VAL	 IDS_STRING572
#define STR_STEP IDS_STRING573

#define PRO_BRIGHTNESS	  IDS_STRING100
#define PRO_CONTRAST	  IDS_STRING101
#define PRO_HUE			  IDS_STRING102
#define PRO_SATURATION	  IDS_STRING103
#define PRO_SHARPNESS	  IDS_STRING104
#define PRO_GAMMA		  IDS_STRING105
#define PRO_COLORENABLE	  IDS_STRING106
#define PRO_WHITEBALANCE  IDS_STRING107
#define PRO_BACKLIGHTCOMP IDS_STRING108
#define PRO_GAIN		  IDS_STRING109

#define PRO_PAN		 IDS_STRING300
#define PRO_TILT	 IDS_STRING301
#define PRO_ROLL	 IDS_STRING302
#define PRO_ZOOM	 IDS_STRING303
#define PRO_EXPOSURE IDS_STRING304
#define PRO_IRIS	 IDS_STRING305
#define PRO_FOCUS	 IDS_STRING306
#define PRO_FLASH	 IDS_STRING307
#define PRO_AIM		 IDS_STRING308

#define ERR_COMSYS IDS_STRING520 
#define ERR_DRIVER IDS_STRING521
#define ERR_GRP_BUILD IDS_STRING523
#define ERR_GMAN IDS_STRING524
#define ERR_CAMI IDS_STRING525
#define ERR_GRP_RUN IDS_STRING538
#define ERR_IDD_IAMVideoProcAmp IDS_STRING539
#define ERR_IDD_IAMCameraControl IDS_STRING540
#define ERR_FLIP_SETUP IDS_STRING542
#define ERR_PROCAMP IDS_STRING545
#define ERR_PROPSET IDS_STRING546
#define ERR_CAMCTRL IDS_STRING547
#define ERR_VIDEO_STOP IDS_STRING555
#define ERR_AUDIO_STOP IDS_STRING556
#define ERR_PREVIEW_STOP IDS_STRING557
#define ERR_VIDEO_ENCODER IDS_STRING560
#define ERR_FORMAT_SET IDS_STRING563
#define ERR_GUN_GET IDS_STRING565
#define ERR_GUN_SET IDS_STRING566
#define ERR_FLIP_SET IDS_STRING568

#define SUC_INIT_FG IDS_STRING522
#define SUC_STILLSETUP IDS_STRING531
#define SUC_PREVIEWSETUP IDS_STRING532
#define SUC_FLIPSETUP IDS_STRING533
#define SUC_GRP_RUN IDS_STRING537
#define SUC_VA_START_EVENT IDS_STRING554
#define SUC_VIDEO_ENCODER IDS_STRING559
#define SUC_FORMAT_SET IDS_STRING562
#define SUC_FLIP_SET IDS_STRING567
#define SUC_CRT_DIR IDS_STRING574

#define STR_CAMNAME IDS_STRING526
#define STR_VSOURCE IDS_STRING527
#define STR_ASOURCE IDS_STRING528
#define STR_DEFFNAME IDS_STRING529
#define STR_DEMARKATE IDS_STRING530
#define STR_STILL_D_F_FMT IDS_STRING534
#define STR_STILL_DIR_PTH IDS_STRING535
#define STR_STILL_FILE_PTH IDS_STRING550
#define STR_STILLSINK IDS_STRING536
#define STR_VRENDERER IDS_STRING543
#define STR_VV_CAP IDS_STRING544
#define STR_JPG IDS_STRING551
#define STR_SFNAME IDS_STRING552
#define STR_VSTART_EVENT IDS_STRING553
#define STR_VIDEO_ENCODER IDS_STRING558
#define STR_NO_OF_CAP IDS_STRING561
#define STR_CLEANUP IDS_STRING564

#endif //HEADERFILE_DSTA_