--- 
name: phone_spec
bbver: 6.0
sdk: ../../
#applog: rholog.txt
version: 1.0.0
vendor: rhomobile
sdkversion: 3.4
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone: 
  sdk: iphonesimulator6.1
  entitlements: ""
  codesignidentity: ""
  configuration: Release
#  extensions: ["barcode"]
  
#wm:
#  extensions: ["barcode"]
  
bb:
  extensions: ["barcode"]
      
capabilities:
  - pim
  - push
  - calendar
  - gps
  - motorola_browser
   
extensions: ["json", "rhoxml", "rhospec", "crypt", "fileutils"]  

wp:
  productid: 'fd55c4d0-51fa-012e-7844-6caec51bd50e'

android:
  apikey: "0tLch9tZSX1G7PQRWwmqvINECUGtJ8ReArpPJxw"
  mapping: enabled
  capabilities:
    - network_state
  extensions: ["barcode"]
  version: 2.3.3
