// WARNING! THIS FILE IS GENERATED AUTOMATICALLY! DO NOT EDIT IT MANUALLY!

#define APP_BUILD_CAPABILITY_NETWORK_STATE
#define APP_BUILD_CAPABILITY_VIBRATE
#define APP_BUILD_CAPABILITY_MOTOROLA_BROWSER
#define APP_BUILD_CAPABILITY_WEBKIT_BROWSER

