// WARNING! THIS FILE IS GENERATED AUTOMATICALLY! DO NOT EDIT IT MANUALLY!

#define APP_BUILD_CAPABILITY_MOTOROLADEV
#define APP_BUILD_CAPABILITY_PIM
#define APP_BUILD_CAPABILITY_SHARED_RUNTIME
#define APP_BUILD_CAPABILITY_SYMBOL
#define APP_BUILD_CAPABILITY_WEBKIT_BROWSER

#define RHO_NO_RUBY
#define RHO_NO_RUBY_API
