// WARNING! THIS FILE IS GENERATED AUTOMATICALLY! DO NOT EDIT IT MANUALLY!

#define APP_BUILD_CAPABILITY_MOTOROLA
#define APP_BUILD_CAPABILITY_MOTOROLADEV
#define APP_BUILD_CAPABILITY_NATIVE_BROWSER

