require 'fileutils'

def build_extension()
  objects = []

  if ENV['RHO_PLATFORM'] == 'wp8'
    args = []
    args = [$project_name + ".vcxproj", "/property:Configuration="+$build_config+" /property:Platform="+$sdk, '/t:Build']
    cmdline = "\"" + $vcbuild + "\"" + ' ' + args.join(' ')
    puts cmdline
    puts `#{cmdline}`
    exit unless $? == 0

  end
end

namespace "build" do
  task :config do
    #$targetdir = ENV['TARGET_TEMP_DIR']
    #raise "TARGET_TEMP_DIR is not set" if $targetdir.nil?

    $tempdir = ENV['TEMP_FILES_DIR']
    raise "TEMP_FILES_DIR is not set" if $tempdir.nil?

    $rootdir = ENV['RHO_ROOT']
    raise "RHO_ROOT is not set" if $rootdir.nil?

    $vcbuild = ENV['VCBUILD']
    raise "VCBUILD is not set" if $vcbuild.nil?

    $sdk = ENV['SDK']
	raise "SDK is not set" if $sdk.nil?
	
	$build_config = ENV['RHO_BUILD_CONFIG']
    raise "RHO_BUILD_CONFIG is not set" if $build_config.nil?

	$project_name = ENV['RHO_PROJECT_NAME']
    raise "RHO_PROJECT_NAME is not set" if $project_name.nil?

  end

  task :all => :config do

    build_extension()
  end
end

task :default => "build:all"
