/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_Platform */

#ifndef _Included_com_rhomobile_rhodes_Platform
#define _Included_com_rhomobile_rhodes_Platform
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_Platform_HTTP_SERVER_STARTED
#define com_rhomobile_rhodes_Platform_HTTP_SERVER_STARTED 1L
#undef com_rhomobile_rhodes_Platform_MAX_PROGRESS
#define com_rhomobile_rhodes_Platform_MAX_PROGRESS 10000L
/*
 * Class:     com_rhomobile_rhodes_Platform
 * Method:    getHomeUrlNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rhomobile_rhodes_Platform_getHomeUrlNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
