/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_Platform */

#ifndef _Included_com_rhomobile_rhodes_Platform
#define _Included_com_rhomobile_rhodes_Platform
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rhomobile_rhodes_Platform_HTTP_SERVER_STARTED
#define com_rhomobile_rhodes_Platform_HTTP_SERVER_STARTED 1L
#undef com_rhomobile_rhodes_Platform_MAX_PROGRESS
#define com_rhomobile_rhodes_Platform_MAX_PROGRESS 10000L
/*
 * Class:     com_rhomobile_rhodes_Platform
 * Method:    startRhodesApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Platform_startRhodesApp
  (JNIEnv *, jobject);

/*
 * Class:     com_rhomobile_rhodes_Platform
 * Method:    stopRhodesApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_Platform_stopRhodesApp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
