/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhomobile_rhodes_datetime_DateTimePicker */

#ifndef _Included_com_rhomobile_rhodes_datetime_DateTimePicker
#define _Included_com_rhomobile_rhodes_datetime_DateTimePicker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhomobile_rhodes_datetime_DateTimePicker
 * Method:    callback
 * Signature: (Ljava/lang/String;J[BZ)V
 */
JNIEXPORT void JNICALL Java_com_rhomobile_rhodes_datetime_DateTimePicker_callback
  (JNIEnv *, jclass, jstring, jlong, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
