/*#pragma once
#if defined(POSIXNAME)
#define fpmkdir _mkdir
#define fpstrnicmp _strnicmp
#define fpfileno _fileno
#define fpaccess _access
#define fpchdir _chdir
#define fpumask _umask
#define fpstrdup _strdup
#define fpdup _dup
#define fpsetmode _setmode
#define fpclose _close
#define fptzet _tzet
#define fpdup2 _dup2
#define fpwcsdup _wcsdup
#define fptzset _tzset
#define fpgetpid _getpid
#define fpexecve _execve
#define fpwrite _write
#define fpfptzset _fptzset
#define fpexecv _execv
#define fpchmod _chmod
#define fpfdopen _fdopen
#define fpeof _eof
#define fpopen _open
#define fpread _read
#else
#define fpmkdir mkdir
#define fpstrnicmp strnicmp
#define fpfileno fileno
#define fpaccess access
#define fpchdir chdir
#define fpumask umask
#define fpstrdup strdup
#define fpdup dup
#define fpsetmode setmode
#define fpclose close
#define fptzet tzet
#define fpdup2 dup2
#define fpwcsdup wcsdup
#define fptzset tzset
#define fpgetpid getpid
#define fpexecve execve
#define fpwrite write
#define fpfptzset fptzset
#define fpexecv execv
#define fpchmod chmod
#define fpfdopen fdopen
#define fpeof eof
#define fpopen open
#define fpread read
#endif*/
