//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsolatedStorageExplorerClient.ClientSessionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientSessionService.IClientSessionService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IClientSessionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientSessionService/GetSessionToken", ReplyAction="http://tempuri.org/IClientSessionService/GetSessionTokenResponse")]
        System.Guid GetSessionToken();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IClientSessionService/Ping", ReplyAction="http://tempuri.org/IClientSessionService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IClientSessionService/EndSession", ReplyAction="http://tempuri.org/IClientSessionService/EndSessionResponse")]
        void EndSession();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientSessionServiceChannel : IsolatedStorageExplorerClient.ClientSessionService.IClientSessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientSessionServiceClient : System.ServiceModel.ClientBase<IsolatedStorageExplorerClient.ClientSessionService.IClientSessionService>, IsolatedStorageExplorerClient.ClientSessionService.IClientSessionService {
        
        public ClientSessionServiceClient() {
        }
        
        public ClientSessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientSessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientSessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientSessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid GetSessionToken() {
            return base.Channel.GetSessionToken();
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public void EndSession() {
            base.Channel.EndSession();
        }
    }
}
