#ifndef RHO_GENCONFIG_H_411BFA4742CF4F2AAA3F6B411ED7514F
#define RHO_GENCONFIG_H_411BFA4742CF4F2AAA3F6B411ED7514F

#define RHO_CAP_AUDIO_ENABLED false
#define RHO_CAP_NETWORK_STATE_ENABLED true
#define RHO_CAP_SDCARD_ENABLED true
#define RHO_CAP_BLUETOOTH_ENABLED true
#define RHO_CAP_VIBRATE_ENABLED true
#define RHO_CAP_PUSH_ENABLED false
#define RHO_CAP_CAMERA_ENABLED true
#define RHO_CAP_PHONE_ENABLED true
#define RHO_CAP_RECORD_AUDIO_ENABLED false
#define RHO_CAP_PIM_ENABLED true
#define RHO_CAP_GPS_ENABLED true
#define RHO_CAP_CALENDAR_ENABLED true

#endif /* RHO_GENCONFIG_H_411BFA4742CF4F2AAA3F6B411ED7514F */
