--- 
name: framework_spec
bbver: 4.6
sdk: /Users/brian/work/rhodes
applog: rholog.txt
version: 1.0.0
vendor: rhomobile
sdkversion: 1.4
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone: 
  sdk: iphonesimulator3.0
  entitlements: ""
  codesignidentity: ""
  configuration: Debug
  extensions: ["digest-md5", "digest-sha1"]  
  
extensions: ["digest", "fcntl", "test-libs"]
