--- 
name: framework_spec
bbver: 4.6
sdk: /Users/brian/work/rhodes
applog: rholog.txt
version: 1.0.0
vendor: rhomobile
sdkversion: 1.4
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone: 
  sdk: iphonesimulator4.0
  entitlements: ""
  codesignidentity: ""
  configuration: Release
  extensions: ["fcntl", "digest-sha1"]   
  
android:    
  extensions: ["digest"]

extensions: ["mspec", "fileutils", "digest", "digest-md5", "test-libs"]
