--- 
name: framework_spec
bbver: 4.6
sdk: ../../
applog: rholog.txt
version: 1.0.0
vendor: rhomobile
sdkversion: 1.4
#wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone: 
  sdk: iphonesimulator4.3
  entitlements: ""
  codesignidentity: ""
  configuration: Release
  #extensions: ["digest-sha1"]   
  
android:    
  version: 2.3.3

extensions: ["mspec", "fileutils", "digest", "digest-md5", "digest-sha1", "test-libs", "set", "thread", "timeout", "uri", "net-http", "fcntl", "rexml" ]
