source 'http://rubygems.org'

gem 'rhoconnect', '3.4.2'
gemfile_path = File.join(File.dirname(__FILE__), ".rcgemfile")

#gem 'aws', '>= 2.6.0'
gem 'aws-s3', '>= 0.6.3'

begin
  eval(IO.read(gemfile_path))
rescue Exception => e
  puts "ERROR: Couldn't read RhoConnect .rcgemfile"
  exit 1
end

# Add your application specific gems after this line ...
