platform :ios, '12.0'
use_frameworks!
#use_modular_headers!

project 'fcm-push.xcodeproj'

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Messaging'

target 'fcm-push' do
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
