//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsolatedStorageExplorerClient.ClientOperationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operation", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations")]
    [System.SerializableAttribute()]
    public partial class Operation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationSessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ClientSessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.RequestBase> OperationsToExecuteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationSessionId {
            get {
                return this.ApplicationSessionIdField;
            }
            set {
                if ((this.ApplicationSessionIdField.Equals(value) != true)) {
                    this.ApplicationSessionIdField = value;
                    this.RaisePropertyChanged("ApplicationSessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClientSessionId {
            get {
                return this.ClientSessionIdField;
            }
            set {
                if ((this.ClientSessionIdField.Equals(value) != true)) {
                    this.ClientSessionIdField = value;
                    this.RaisePropertyChanged("ClientSessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.RequestBase> OperationsToExecute {
            get {
                return this.OperationsToExecuteField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationsToExecuteField, value) != true)) {
                    this.OperationsToExecuteField = value;
                    this.RaisePropertyChanged("OperationsToExecute");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.DeleteFileRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.DeleteDirectoryRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.UploadFileRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.DownloadFileRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.CreateDirectoryRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteFileRequest", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations")]
    [System.SerializableAttribute()]
    public partial class DeleteFileRequest : IsolatedStorageExplorerClient.ClientOperationService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteDirectoryRequest", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations.Requests")]
    [System.SerializableAttribute()]
    public partial class DeleteDirectoryRequest : IsolatedStorageExplorerClient.ClientOperationService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectoryPathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectoryPath {
            get {
                return this.DirectoryPathField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoryPathField, value) != true)) {
                    this.DirectoryPathField = value;
                    this.RaisePropertyChanged("DirectoryPath");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadFileRequest", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations.Requests")]
    [System.SerializableAttribute()]
    public partial class UploadFileRequest : IsolatedStorageExplorerClient.ClientOperationService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UploadStreamIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UploadStreamId {
            get {
                return this.UploadStreamIdField;
            }
            set {
                if ((this.UploadStreamIdField.Equals(value) != true)) {
                    this.UploadStreamIdField = value;
                    this.RaisePropertyChanged("UploadStreamId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadFileRequest", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations.Requests")]
    [System.SerializableAttribute()]
    public partial class DownloadFileRequest : IsolatedStorageExplorerClient.ClientOperationService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DownloadStreamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DownloadStreamId {
            get {
                return this.DownloadStreamIdField;
            }
            set {
                if ((this.DownloadStreamIdField.Equals(value) != true)) {
                    this.DownloadStreamIdField = value;
                    this.RaisePropertyChanged("DownloadStreamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateDirectoryRequest", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations.Requests")]
    [System.SerializableAttribute()]
    public partial class CreateDirectoryRequest : IsolatedStorageExplorerClient.ClientOperationService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectoryPathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectoryPath {
            get {
                return this.DirectoryPathField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoryPathField, value) != true)) {
                    this.DirectoryPathField = value;
                    this.RaisePropertyChanged("DirectoryPath");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationProgress", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations.OperationProgress")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.OperationFailedDueToException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.OperationCompleted))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.OperationCanceled))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.OperationReceived))]
    public partial class OperationProgress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OperationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalProgressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OperationId {
            get {
                return this.OperationIdField;
            }
            set {
                if ((this.OperationIdField.Equals(value) != true)) {
                    this.OperationIdField = value;
                    this.RaisePropertyChanged("OperationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalProgress {
            get {
                return this.TotalProgressField;
            }
            set {
                if ((this.TotalProgressField.Equals(value) != true)) {
                    this.TotalProgressField = value;
                    this.RaisePropertyChanged("TotalProgress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationFailedDueToException", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations.OperationProgress")]
    [System.SerializableAttribute()]
    public partial class OperationFailedDueToException : IsolatedStorageExplorerClient.ClientOperationService.OperationProgress {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FailedRequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsolatedStorageExplorerClient.ClientOperationService.IsolatedStorageInformation NewIsolatedStorageInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FailedRequestId {
            get {
                return this.FailedRequestIdField;
            }
            set {
                if ((this.FailedRequestIdField.Equals(value) != true)) {
                    this.FailedRequestIdField = value;
                    this.RaisePropertyChanged("FailedRequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IsolatedStorageExplorerClient.ClientOperationService.IsolatedStorageInformation NewIsolatedStorageInformation {
            get {
                return this.NewIsolatedStorageInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.NewIsolatedStorageInformationField, value) != true)) {
                    this.NewIsolatedStorageInformationField = value;
                    this.RaisePropertyChanged("NewIsolatedStorageInformation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationCompleted", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations.OperationProgress")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsolatedStorageExplorerClient.ClientOperationService.OperationCanceled))]
    public partial class OperationCompleted : IsolatedStorageExplorerClient.ClientOperationService.OperationProgress {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsolatedStorageExplorerClient.ClientOperationService.IsolatedStorageInformation NewIsolatedStorageInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IsolatedStorageExplorerClient.ClientOperationService.IsolatedStorageInformation NewIsolatedStorageInformation {
            get {
                return this.NewIsolatedStorageInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.NewIsolatedStorageInformationField, value) != true)) {
                    this.NewIsolatedStorageInformationField = value;
                    this.RaisePropertyChanged("NewIsolatedStorageInformation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationCanceled", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations.OperationProgress")]
    [System.SerializableAttribute()]
    public partial class OperationCanceled : IsolatedStorageExplorerClient.ClientOperationService.OperationCompleted {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CancelTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CancelTime {
            get {
                return this.CancelTimeField;
            }
            set {
                if ((this.CancelTimeField.Equals(value) != true)) {
                    this.CancelTimeField = value;
                    this.RaisePropertyChanged("CancelTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationReceived", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts.Oper" +
        "ations.OperationProgress")]
    [System.SerializableAttribute()]
    public partial class OperationReceived : IsolatedStorageExplorerClient.ClientOperationService.OperationProgress {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReceiveTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReceiveTime {
            get {
                return this.ReceiveTimeField;
            }
            set {
                if ((this.ReceiveTimeField.Equals(value) != true)) {
                    this.ReceiveTimeField = value;
                    this.RaisePropertyChanged("ReceiveTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsolatedStorageInformation", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts")]
    [System.SerializableAttribute()]
    public partial class IsolatedStorageInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AvailableSpaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.DirectoryInformation> DirectoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.FileInformation> FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QuotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AvailableSpace {
            get {
                return this.AvailableSpaceField;
            }
            set {
                if ((this.AvailableSpaceField.Equals(value) != true)) {
                    this.AvailableSpaceField = value;
                    this.RaisePropertyChanged("AvailableSpace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.DirectoryInformation> Directories {
            get {
                return this.DirectoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoriesField, value) != true)) {
                    this.DirectoriesField = value;
                    this.RaisePropertyChanged("Directories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.FileInformation> Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Quota {
            get {
                return this.QuotaField;
            }
            set {
                if ((this.QuotaField.Equals(value) != true)) {
                    this.QuotaField = value;
                    this.RaisePropertyChanged("Quota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectoryInformation", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts")]
    [System.SerializableAttribute()]
    public partial class DirectoryInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.DirectoryInformation> DirectoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.FileInformation> FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.DirectoryInformation> Directories {
            get {
                return this.DirectoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoriesField, value) != true)) {
                    this.DirectoriesField = value;
                    this.RaisePropertyChanged("Directories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<IsolatedStorageExplorerClient.ClientOperationService.FileInformation> Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileInformation", Namespace="http://schemas.datacontract.org/2004/07/ExplorerService.Common.DataContracts")]
    [System.SerializableAttribute()]
    public partial class FileInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientOperationService.IClientOperationService", CallbackContract=typeof(IsolatedStorageExplorerClient.ClientOperationService.IClientOperationServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IClientOperationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientOperationService/StartOperationSession", ReplyAction="http://tempuri.org/IClientOperationService/StartOperationSessionResponse")]
        void StartOperationSession(System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/IClientOperationService/CancelOperation", ReplyAction="http://tempuri.org/IClientOperationService/CancelOperationResponse")]
        void CancelOperation(System.Guid operationId);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IClientOperationService/PostOperation", ReplyAction="http://tempuri.org/IClientOperationService/PostOperationResponse")]
        bool PostOperation(IsolatedStorageExplorerClient.ClientOperationService.Operation operation);
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IClientOperationService/EndOperationSession", ReplyAction="http://tempuri.org/IClientOperationService/EndOperationSessionResponse")]
        void EndOperationSession();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientOperationServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IClientOperationService/OperationProgress")]
        void OperationProgress(System.Guid applicationSessionId, IsolatedStorageExplorerClient.ClientOperationService.OperationProgress progress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientOperationServiceChannel : IsolatedStorageExplorerClient.ClientOperationService.IClientOperationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientOperationServiceClient : System.ServiceModel.DuplexClientBase<IsolatedStorageExplorerClient.ClientOperationService.IClientOperationService>, IsolatedStorageExplorerClient.ClientOperationService.IClientOperationService {
        
        public ClientOperationServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ClientOperationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ClientOperationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientOperationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientOperationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void StartOperationSession(System.Guid sessionId) {
            base.Channel.StartOperationSession(sessionId);
        }
        
        public void CancelOperation(System.Guid operationId) {
            base.Channel.CancelOperation(operationId);
        }
        
        public bool PostOperation(IsolatedStorageExplorerClient.ClientOperationService.Operation operation) {
            return base.Channel.PostOperation(operation);
        }
        
        public void EndOperationSession() {
            base.Channel.EndOperationSession();
        }
    }
}
