#!/bin/sh


if [ "$RHO_PLATFORM" = "android" ]; then

cd <%= name.downcase %>/platform/android
rake --trace

elif [ "$RHO_PLATFORM" = "iphone" ]; then

cd <%= name.downcase %>/platform/iphone
rake --trace

fi



